### ISSUE TITLE
Rearrange  the layout

### ISSUE THREAD

**Issue by pan1fan2** [UBC-MDS/mds532_viz_group25#13]
Based on lab 2 instruction and feedbacks,  let us rearrange the layout on the dashboard to have 2 plots.

The line chart on the left displays the evolution of total violent crime in the city of interest

The bar chart on the right displays violent crime in 4 types at the city of interest at  different years
.

**Comment by Julie-M-Zhu** [comment]
I have checked the prototype and the deployment on the website, everything goes perfectly.
