### ISSUE TITLE
Include screenshot of entire dashboard

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/mds532_viz_group25#19]
Hey group 25! Could I ask that you include a screenshot of your entire dashboard in the repo root as a gif image or video? I would need this to create a nice thumbnail for you inthe gallery I am making, now I am just getting one of the bar plots. I took a screenshot and converted it to a gif for you, so if you want you can just save this file in the repo root.

![grp25-dashboard](https://user-images.githubusercontent.com/4560057/107131719-bddd3380-688d-11eb-99c8-f20e5be477ce.gif)

Also don't forget to fill out the info in the top right corner of your github home page before you submit tonight!

![image](https://user-images.githubusercontent.com/4560057/107131750-23312480-688e-11eb-873f-3e9aeda531ad.png)

**Comment by pan1fan2** [comment]
Hi Joel,

Thanks a lot for making the .gif file for us. We have included this in our readme.  And the About section has been updated. Thanks again for reminding us. I 

Best regards,
Group 25

**Comment by joelostblom** [comment]
Great!
